name: Clang-Format

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  clang-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      - name: Install clang-format-18
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 18
          sudo apt-get update
          sudo apt-get install -y clang-format-18

      - name: Run clang-format
        run: ./clang_format_all.sh
        
      - name: Check formatting
        run: git diff --exit-code --diff-filter=d --color
